require("trouble").setup()

vim.keymap.set("n", "<leader>xx", vim.cmd.TroubleToggle, { desc = "Open Diagnostics" })
vim.keymap.set("n", "<leader>xw", function()
    vim.cmd.TroubleToggle("workspace_diagnostics")
end, { desc = "Open Workspace Trouble" })
vim.keymap.set("n", "<leader>xd", function()
    vim.cmd.TroubleToggle("document_diagnostics")
end, { desc = "Open Document Trouble" })
vim.keymap.set("n", "<leader>xq", function()
    vim.cmd.TroubleToggle("quickfix")
end, { desc = "Open Quickfix Trouble" })
vim.keymap.set("n", "<leader>xl", function()
    vim.cmd.TroubleToggle("loclist")
end, { desc = "Open Loclist Trouble" })
vim.keymap.set("n", "gR", function()
    vim.cmd.TroubleToggle("lsp_references")
end, { desc = "Open Loclist Trouble" })
