return {
  require('odie.plugins.configs.minipairs'),
  require('odie.plugins.configs.minimove'),
  require('odie.plugins.configs.nvim-lastplace'),
  require('odie.plugins.configs.vim-surround'),
  require('odie.plugins.configs.vim-repeat'),
  require('odie.plugins.configs.vim-sleuth'),
  require('odie.plugins.configs.vim-illuminate'),
  require('odie.plugins.configs.indent-blankline'),
  require('odie.plugins.configs.nvim-colorizer'),
  require('odie.plugins.configs.sentiment'),
  require('odie.plugins.configs.Comment'),
  require('odie.plugins.configs.nvim-lightbulb'),
  require('odie.plugins.configs.nvim-code-action-menu'),
  require('odie.plugins.configs.undotree'),
}
